Repository HackSquadDev/contributor-of-the-xxx-python, pull requests merged in 2022-10, with the labels that each got.

#5 Added headless operation (work in progress) and configuration files.
  .env.example
  .flake8
  .gitignore
  requirements.txt
  src/bot.py
Labels: enhancement

#6 Added GitHub Actions workflow for linting.
  .flake8
  .github/workflows/linting.yml
  src/bot.py
Labels: enhancement

#8 use aiohttp instead of requests
  src/bot.py
Labels: enhancement

#9 Update bot.py
  src/bot.py
Labels: enhancement

#10 Added primary support for Docker and a kickstarter README.
  .dockerignore
  .flake8
  Dockerfile
  README.md
  docker-compose.yml
Labels: enhancement

#13 Get top contributor
  .gitignore
  src/bot.py
Labels: enhancement

#15 Added contributor model for data and refactored code.
  .env.example
  .flake8
  models/__init__.py
  models/contributor.py
  src/bot.py
Labels: enhancement

#16 Add organization model
  models/__init__.py
  models/contributor.py
  models/organization.py
  src/bot.py
Labels: enhancement

#17 Refactored codebase and added configuration for VSCode.
  .flake8
  .gitignore
  .vscode/settings.json
  main.py
  models/contributor.py
  models/organization.py
  src/bot.py
Labels: enhancement

#18 Image now stored in bytes and removed non-async URL calls.
  models/contributor.py
  requirements.txt
  src/bot.py
Labels: enhancement

#21 refactor: add 'discord_webhook` to the dependencies
  requirements.txt
Labels: bug-fixed

#22 feat: add pre-commit and autoformatting to the code
  .pre-commit-config.yaml
  .vscode/settings.json
  models/contributor.py
  models/organization.py
  requirements.txt
  src/bot.py
  src/utils/functions.py
Labels: enhancement

#23 only process prs created before a certain date
  .gitignore
  requirements.txt
  src/bot.py
Labels: enhancement

#31 Improved overlay, removed libraqm and more.
  Dockerfile
  README.md
  assets/overlay.png
  models/contributor.py
Labels: enhancement

#36 Added simple test mode, fixed dependencies and small changes.
  main.py
  models/contributor.py
  requirements.txt
  src/bot.py
  src/global_.py
Labels: enhancement

#38 Obtain Issue count for the contributors
  src/bot.py
Labels: enhancement

#47 chore: add the option to bot execute once at startup
  main.py
  src/bot.py
Labels: enhancement

#46 feat: Added random quotes for image manipulation.
  README.md
  models/contributor.py
  requirements.txt
Labels: enhancement

#48 chore: Bot runs once every startup; fixed type hints and more.
  main.py
  models/contributor.py
  src/bot.py
Labels: enhancement

#51 refactor: fix crucial error
  src/bot.py
Labels: enhancement

#49 refactor: Optimize the API calls
  src/bot.py
Labels: enhancement

#52 refactor: Rewritten environment handler from scratch
  models/contributor.py
  requirements.txt
  src/__init__.py
  src/bot.py
  src/global_.py
  src/settings.py
Labels: enhancement, bug-fixed

#53 feat: Added "Contributor of the Week" to output image.
  assets/background.png
  assets/overlay.png
  models/contributor.py
Labels: enhancement

#55 feat: Added dynamic "Contributor of the What" header
  assets/background.png
  models/contributor.py
Labels: enhancement

#56 visual: Updated banner design.
  assets/background.png
  assets/overlay.png
Labels: enhancement

#58 chore: make the message dynamic like the image
  models/contributor.py
Labels: enhancement

#57 chore: handled exceptions
  src/bot.py
Labels: enhancement

#60 chore: Synced black configuration, new workflow automation and more.
  .github/workflows/formatting.yml
  pyproject.toml
  src/bot.py
Labels: enhancement

#61 chore: Improved docs and added license
  LICENSE
  README.md
Labels: documentation

#64 refactor: Add image saving to test mode.
  .gitignore
  Dockerfile
  models/contributor.py
  src/bot.py
Labels: enhancement

#70 Fix: Test Mode malfunction
  src/bot.py
Labels: bug-fixed

#71 bugfix: Fixed text duplication in Twitter tweet & Discord message
  models/contributor.py
Labels: bug-fixed

#74 Manage None bios
  models/contributor.py
Labels: enhancement

#75 chore: Polished background and overlay.
  assets/background.png
  assets/overlay.png
Labels: documentation
